reward_scale: 1
batch_size: 68
baseline_mode: none
decay: 6.4e-05
lr: 0.0009305
demand_scale: 0.806407
n_routes: 1
n_epochs: 10
space_scale: 0.999166
optimizer: Adam
outdir: outputs
dataset: datasets/20_nodes/mixed
eval_n_routes: [1, 2, 6, 8, 10]

model:
  common:
    embed_dim: 128
    nonlin_type: LeakyReLU
    dropout: 0.22016
    
  route_generator:
    feat_alpha: 0.0006638419144265608
    mask_used_paths: False
    n_nodepair_layers: 3
    n_scorelenfn_layers: 1
    use_extra_dmd_feats: True
    use_extra_route_feats: False

  env_gn:
    net_type: sgc
    kwargs:
      n_layers: 1
      in_node_dim: 8
      in_edge_dim: 2
      use_norm: False

  route_gn:
    net_type: edge graph
    kwargs:
      n_layers: 3
      in_edge_dim: 1
      dense: False
      recurrent: False
      residual: False
      use_norm: False
      layer_kwargs:
        n_edge_layers: 2


defaults:
  - experiment: standard